### ISSUE TITLE
Question on porting to STM32H750

### ISSUE THREAD

**Issue by krcurtis** [JCGobbi/Nucleo-STM32H743ZI#1]
Hi,

How much effort would it be to port this to the STM32H750 IBKx, used on the daisy seed? Any tips on porting, using your code as a base?

Some daisy seed info at
- https://github.com/electro-smith/DaisyWiki/wiki

I'm hoping the STM32H743 is similar to make it easier, because I haven't tried to port an Ada runtime before. Also I think I need to use the Ravenscar profile for the real-time support (for audio) (Ada.Real_Time and delay until)

Thanks!

**Comment by JCGobbi** [comment]
The STM32H750 has the same processing unit than STM32H743 and the same SRAM memory length and address map. The same occurs with the peripherals, that have the same quantities and address map. So the Ada drivers that I have developed for the STM32H743 don't need to change.

For the run-times you only need to change the FLASH memory LENGTH in the file memory-map.ld. You have two options:
1. Change the file bb-runtimes/arm/stm32/stm32h743/memory-map.ld and regenerate the run-times, or
2. Change this same parameter in the already generated run-times inside the files ADL/runtimes/embedded-stm32h743/ld/memory-map.ld and ADL/runtimes/light-tasking-stm32h743/ld/memory-map.ld, and you don't need to regenerate the run-times.

Below is the change for the FLASH LENGTH from 2048k to 128k that you need to do in the file memory-map.ld:

```sh
MEMORY
{
FLASH (rx)     : ORIGIN = 0x08000000, LENGTH = 128K /* Flash memory */
ITCM (xrw)     : ORIGIN = 0x00000000, LENGTH = 64K /* ITCM */
DTCM (xrw)     : ORIGIN = 0x20000000, LENGTH = 128K /* DTCM */
SRAM_AXI (xrw) : ORIGIN = 0x24000000, LENGTH = 512K /*  AXI SRAM */
SRAM123 (xrw)  : ORIGIN = 0x30000000, LENGTH = 288K /* SRAM 1,2 and 3 */
SRAM4 (xrw)    : ORIGIN = 0x38000000, LENGTH = 64K /* SRAM4 */
RAM_BKP (xrw)  : ORIGIN = 0x38800000, LENGTH = 4K /* Backup SRAM */
}
```

And that's all for the ADL and run-times. Test them with a simple LED blinking program. Good Luck!
